services:
  # Service pour le frontend Vite/React
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_API=http://localhost:8000/api/v1 # Backend
    depends_on: # Le front ne démarre pas tant que le backend n'a pas démarré
      - backend
    volumes: # Conservation du code et des modules dans le conteneur
      - ./front:/app
      - /app/node_modules
    restart: no

  # Conteneur éphémère pour les migrations
  migration:
    image: postgres:15-alpine
    volumes:
      - ./scripts:/scripts        # Monte ton dossier scripts
      - ./migrations:/migrations  # Monte ton dossier de fichiers .sql
    working_dir: /                # On se met à la racine
    entrypoint: /bin/sh           # On force le shell
    command: /scripts/migrate.sh
    environment:
      - PGPASSWORD=postgres       # Évite que psql ne demande le mot de passe
    depends_on:
      db:
        condition: service_healthy

  # Service backend (FastAPI + Poetry)
  backend:
    build: ./back
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/localdb
      - DB_HOST=db
      - DB_PORT=5432
    depends_on: # Le service ne démarre pas tant que la db n'a pas été initialisée
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    volumes: # Conservation du code dans le conteneur
      - ./back:/app
    restart: no

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localdb
    ports:
      - "5000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d localdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no
# Volume pour persister les données de PostgreSQL
volumes:
  postgres_data:
