"""create_user_stravoska_table

Revision ID: 09d653bd3d49
Revises: 
Create Date: 2026-01-02 17:08:38.995745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d653bd3d49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stravoska',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stravoska_email'), 'user_stravoska', ['email'], unique=True)
    op.create_index(op.f('ix_user_stravoska_id'), 'user_stravoska', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stravoska_id'), table_name='user_stravoska')
    op.drop_index(op.f('ix_user_stravoska_email'), table_name='user_stravoska')
    op.drop_table('user_stravoska')
    # ### end Alembic commands ###
